package orchestrator

import "context"

// CannedBrain is the M1 placeholder Brain: deterministic, no model calls. It
// lets `wazir serve` drive the deterministic transitions until the real claude
// runner (internal/claude) replaces it in M2.
type CannedBrain struct{}

func (CannedBrain) Brainstorm(ctx context.Context, in BrainstormInput) (BrainstormResult, error) {
	return BrainstormResult{
		Status:       SpecReady,
		SpecMarkdown: "## Spec (placeholder)\n\n_Generated by the M1 CannedBrain; the real spec arrives in M2._",
	}, nil
}

func (CannedBrain) Plan(ctx context.Context, in PlanInput) (PlanResult, error) {
	return PlanResult{Status: StatusPlanReady, PlanPath: "docs/plan.md", Summary: "placeholder plan"}, nil
}

func (CannedBrain) Execute(ctx context.Context, in ExecuteInput) (ExecuteResult, error) {
	return ExecuteResult{Status: StatusComplete, Branch: "wazir/placeholder", TestSummary: "n/a"}, nil
}

func (CannedBrain) Rework(ctx context.Context, in ReworkInput) (ReworkResult, error) {
	return ReworkResult{Status: StatusComplete, Notes: "canned rework"}, nil
}

var _ Brain = CannedBrain{}
