name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  vet:
    name: Go vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: go vet
        run: go vet ./...

  test:
    name: Go build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
